export const SET_IS_CREATE_NEW_BOARD_MODAL_OPEN = 'SET_IS_CREATE_NEW_BOARD_MODAL_OPEN';

export enum ActionKindAppState {
  SET_IS_CREATE_NEW_BOARD_MODAL_OPEN = 'SET_IS_CREATE_NEW_BOARD_MODAL_OPEN',
}